---

- name: generate .toolboxrc
  script: >
      coreos-toolboxrc-generate.sh
        {{ toolboxrc_image_archive_url or ""|quote }}
        {{ toolboxrc_image_name or ""|quote }}
        {{ toolboxrc_image_tag or ""|quote }}
        {{ 1 if toolboxrc_image_import_from_docker else 0 }}
