#! /bin/bash

set -e

cd

IMG_URL=$1
IMG_NAME=$2
IMG_TAG=$3
IMPORT_FROM_DOCKER=$4

RC_FILE=.toolboxrc

# header
cat     >  ${RC_FILE}       <<'EOF'
# This file is generated by coreos-toolbox.
#
#   $(date)
# 
X_IMG_NAME=${TOOLBOX_DOCKER_IMAGE}
X_IMG_TAG=${TOOLBOX_DOCKER_TAG}
EOF

if [[ -n "${IMG_NAME}" ]]; then
    echo    "TOOLBOX_DOCKER_IMAGE=${IMG_NAME}"      >>   ${RC_FILE}
    echo    "X_IMG_NAME=${IMG_NAME}"                >>   ${RC_FILE}
fi

if [[ -n "${IMG_TAG}" ]]; then
    echo    "TOOLBOX_DOCKER_TAG=${IMG_TAG}"         >>   ${RC_FILE}
    echo    "X_IMG_TAG=${IMG_TAG}"                  >>   ${RC_FILE}
fi

if [[ -n "${IMG_URL}" ]]; then
    echo '
unset   TOOLBOX_DOCKER_IMAGE
unset   TOOLBOX_DOCKER_TAG
TOOLBOX_NAME=${X_IMG_NAME}-${X_IMG_TAG}
TOOLBOX_DOCKER_ARCHIVE=${IMG_URL}
    '   >>  ${RC_FILE}
fi

if  [ "${IMPORT_FROM_DOCKER}" == "1" ]; then
cat     >>  ${RC_FILE}  <<'EOF'
machinename=$(echo "${USER}-${X_IMG_NAME}-${X_IMG_TAG}" | sed -r 's/[^a-zA-Z0-9_.-]/_/g')
machinepath="${TOOLBOX_DIRECTORY}/${machinename}"
osrelease="${machinepath}/etc/os-release"
if [ ! -f "${osrelease}" ]; then
    tmpdir=$(mktemp -d -p /var/tmp/)
    tmpfile=${tmpdir}/docker-${X_IMG_NAME}-${X_IMG_TAG}.tar
    trap "sudo rm -rf ${tmpdir}" EXIT PIPE
    docker pull "${X_IMG_NAME}:${X_IMG_TAG}" || exit    1
    docker save "${X_IMG_NAME}:${X_IMG_TAG}" -o "${tmpfile}" || exit    1
    sudo tar -C ${tmpdir} -xf "${tmpfile}"
    sudo mkdir -p ${machinepath}
    sudo find ${tmpdir} -name layer.tar -type f -exec tar -C ${machinepath} -xf {} \;
    trap - EXIT PIPE
    sudo rm -rf ${tmpdir}
fi
EOF
fi

chmod   644     ${RC_FILE}
