#! /bin/bash

set -e

cd

IMG_URL=$1
IMG_NAME=$2
IMG_TAG=$3

RC_FILE=.toolboxrc

# header
cat     >  ${RC_FILE}       <<EOF
# This file is generated by coreos-toolbox.
#
#   $(date)
# 
EOF

if [[ -n "${IMG_URL}" ]]; then
    echo '
X_IMG_NAME=${TOOLBOX_DOCKER_IMAGE}
X_IMG_TAG=${TOOLBOX_DOCKER_TAG}
    '   >>  ${RC_FILE}
fi

if [[ -n "${IMG_NAME}" ]]; then
    echo    "TOOLBOX_DOCKER_IMAGE=${IMG_NAME}"      >>   ${RC_FILE}
    if [[ -n "${IMG_URL}" ]]; then
        echo    "X_IMG_NAME=${IMG_NAME}"            >>   ${RC_FILE}
    fi
fi

if [[ -n "${IMG_TAG}" ]]; then
    echo    "TOOLBOX_DOCKER_TAG=${IMG_TAG}"         >>   ${RC_FILE}
    if [[ -n "${IMG_URL}" ]]; then
        echo    "X_IMG_TAG=${IMG_TAG}"              >>   ${RC_FILE}
    fi
fi

if [[ -n "${IMG_URL}" ]]; then
    echo '
TOOLBOX_NAME=${X_IMG_NAME}-${X_IMG_TAG}
TOOLBOX_DOCKER_ARCHIVE=${IMG_URL}
    '   >>  ${RC_FILE}
fi

chmod   644     ${RC_FILE}
